# Generated by Django 4.2.23 on 2025-08-24 06:46

import base.models.restaurant_models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='カテゴリ名')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='スラッグ')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='タグ名')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='スラッグ')),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.CharField(default=base.models.restaurant_models.restaurant_pk, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
                ('regular_holiday', models.CharField(blank=True, default='', max_length=50)),
                ('special_holiday', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='', upload_to=base.models.restaurant_models.upload_image_to)),
                ('rating', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='base.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='restaurants', to='base.tag')),
            ],
        ),
    ]
