# Generated by Django 4.2.23 on 2025-08-25 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='budget',
            field=models.IntegerField(default=0, help_text='1人あたりの平均予算（円）', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
    ]
