# Generated by Django 4.2.23 on 2025-09-16 11:53

import base.models.subscription_models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_member_birthday_member_job_member_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='code',
            field=models.CharField(choices=[('free', 'Free'), ('subscribed', 'Subscribed')], max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='special_holiday',
            field=models.ManyToManyField(blank=True, to='base.specialholiday'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.CharField(default=base.models.subscription_models.subscription_pk, max_length=50, primary_key=True, serialize=False),
        ),
    ]
