# Generated by Django 4.2.23 on 2025-09-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_subscription_member_alter_membershiptype_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='regular_holiday',
            field=models.ManyToManyField(blank=True, to='base.holiday'),
        ),
    ]
