# Generated by Django 4.2.23 on 2025-09-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_restaurant_address_restaurant_zipcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='closing_time',
            field=models.TimeField(blank=True, help_text='例: 22:00', null=True, verbose_name='閉店時間'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_time',
            field=models.TimeField(blank=True, help_text='例: 09:00', null=True, verbose_name='開店時間'),
        ),
    ]
