# Generated by Django 4.2.23 on 2025-09-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_restaurant_closing_time_restaurant_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
