# Generated by Django 5.2.6 on 2025-10-15 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_reservation_cancel_reason_reservation_canceled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_by', to='base.restaurant'),
        ),
    ]
