# Generated by Django 5.2.6 on 2025-10-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_favorite_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='stripe_card_brand',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Stripeカードブランド'),
        ),
        migrations.AddField(
            model_name='member',
            name='stripe_card_exp_month',
            field=models.IntegerField(default=0, verbose_name='Stripeカード有効月'),
        ),
        migrations.AddField(
            model_name='member',
            name='stripe_card_exp_year',
            field=models.IntegerField(default=0, verbose_name='Stripeカード有効年'),
        ),
        migrations.AddField(
            model_name='member',
            name='stripe_card_last4',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Stripeカード下4桁'),
        ),
        migrations.AddField(
            model_name='member',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='StripeカスタマーID'),
        ),
        migrations.AddField(
            model_name='member',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='StripeサブスクリプションID'),
        ),
    ]
